### PR TITLE
added support for transactions

### PR DESCRIPTION
**Pull request by acoburn**
Resolves: https://jira.duraspace.org/browse/FCREPO-1349

added support for transactions
added unit and integration tests
added documentation for transactions

### CODE REVIEW

**Comment by ajs6f** [comment]
Any thoughts about integrating with [Camel transactions](https://camel.apache.org/transactional-client.html)?

**Comment by acoburn** [comment]
@ajs6f that is quite a good idea. I am not familiar with the camel transactional-client, but off the cuff it looks like the better approach. This would require a different implementation, but that's not a problem.

**Comment by ajs6f** [comment]
Transactions should be seen and not heard.

**Comment by acoburn** [comment]
:+1:

**Comment by acoburn** [comment]
This PR should be deprecated in favor of https://github.com/fcrepo4/fcrepo-camel/pull/59

**Pull request closed without merging**
